packages:
  # all packages in direct sub directories of apps/
  - "apps/*"
  # all unstable packages
  - "packages/_unstable_/*"
  # all tooling packages
  - "packages/tooling/*"
  # all standard ui component packages
  - "packages/ui/components/*"
    # all core ui component packages
  - "packages/ui/core/*"
  # all layout component packages
  - "packages/ui/layout/*"
  # all typography component packages
  - "packages/ui/typograpy/*"
  # all utility packages
  - "packages/utils/*"
  # all packages in a benchmark sub directory
  - "**/benchmark"
