packages:
  # all packages in direct sub directories of apps/
  - "apps/*"
  # all packages in direct sub directories of packages/
  - "packages/*"
    # all packages in direct sub directories of ui/
  - "ui/*"
