name: Turbo Test

on: [workflow_call, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Turbo Test
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Setup Environment
        uses: clutchd/turbostart-npm@v1.0.1

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3
        if: ${{ !cancelled() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "**/clover.xml"

      - name: Create Release Pull Request or Publish to npm
        if: ${{ github.ref == 'refs/heads/main' }}
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
