name: Turbo Test

on: [workflow_call, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Turbo Test
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 2

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm i

      # - name: Bun Runtime
      #   id: setup-bun
      #   uses: oven-sh/setup-bun@v1
      #   with:
      #     bun-version: latest

      - name: Lint
        id: lint
        run: pnpm lint

      - name: Build
        id: build
        run: pnpm build

      - name: Test
        id: test
        run: pnpm test

      - name: Upload Code Coverage
        id: codecov
        uses: codecov/codecov-action@v4
        if: ${{ github.ref == 'refs/heads/main' && steps.test.outcome == 'success' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "**/clover.xml"

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        if: ${{ github.ref == 'refs/heads/main' && !cancelled() }}
        uses: changesets/action@v1
        with:
          publish: pnpm run release
