name: Turbo Test

on: [workflow_call, push]

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
  test:
    needs: setup
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3
        if: ${{ !cancelled() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "**/clover.xml"
