name: Turbo Test

on: [workflow_call, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Turbo Test
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Setup Environment
        id: setup
        uses: clutchd/turbostart-pnpm@v3.0.0

      - name: Bun Runtime
        id: setup-bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Lint
        id: lint
        run: bun run lint

      - name: Test
        id: test
        run: bun run test

      - name: Upload Code Coverage
        id: codecov
        uses: codecov/codecov-action@v3
        if: ${{ github.ref == 'refs/heads/main' && steps.test.outcome == 'success' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "**/clover.xml"

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        if: ${{ github.ref == 'refs/heads/main' && !cancelled() }}
        uses: changesets/action@v1
        with:
          publish: bun run release
